#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build
source build/envsetup.sh
lunch rr_certus-userdebug
export LC_ALL=C
export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	make api-stubs-docs
	make system-api-stubs-docs
	make test-api-stubs-docs
}

make_rom(){
	make bacon -j8
	zip=$(up out/target/product/certus/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 5200 && kill "$!"
