#!/bin/bash

url=https://drive.netterz.my.id/ccache-cr-6.1.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache-cr-6.1.tar.gz
echo "unzip done"
find ccache-cr-6.1.tar.gz -delete
