#!/bin/bash

url=https://hidden-salad-60dc.unnamed877.workers.dev/ccache-rr-8.6.7.tar.gz

#cd /tmp # Where to download cccahe
#time aria2c $url -x16 -s50
#echo "dl done"
#time tar xf ccache-rr-8.6.7.tar.gz
echo "unzip done"
#find ccache-rr-8.6.7.tar.gz -delete
