#!/bin/bash

MANIFEST=https://github.com/CarbonROM/android.git
BRANCH=cr-6.1

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Azfasa15
git config --global user.email Azfasa15@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone https://github.com/wulan17/android_device_xiaomi_mt6765-common -b lineage-15.1 device/xiaomi/mt6765-common
git clone https://github.com/wulan17/proprietary_vendor_xiaomi -b lineage-15.1 vendor/xiaomi
git clone https://github.com/Rodeobazaar124/android_device_xiaomi_cactus -b cr-6.1 device/xiaomi/cactus
git clone --depth=1 --single-branch https://github.com/wulan17/android_kernel_xiaomi_mt6765 -b oreo kernel/xiaomi/mt6765
