#!/bin/bash

MANIFEST=https://github.com/NusantaraProject-ROM/android_manifest
BRANCH=11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name adlin
git config --global user.email adlin@mayumi-chan.git

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone https://github.com/rulim34/device_xiaomi_riva-old.git -b eleven device/xiaomi/riva
git clone https://github.com/rulim34/vendor_xiaomi_riva-old.git -b eleven vendor/xiaomi/riva
git clone --depth=1 https://github.com/kdrag0n/proton-clang.git prebuilts/clang/host/linux-x86/clang-proton
git clone https://github.com/Thagoo/platform_kernel_xiaomi_msm8917 -b lineage-18.1 kernel/xiaomi/msm8917
